export const mockedUser = {
	login: 'arpit8392',
	id: 16048172,
	node_id: 'MDQ6VXNlcjE2MDQ4MTcy',
	avatar_url: 'https://avatars.githubusercontent.com/u/16048172?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/arpit8392',
	html_url: 'https://github.com/arpit8392',
	followers_url: 'https://api.github.com/users/arpit8392/followers',
	following_url:
		'https://api.github.com/users/arpit8392/following{/other_user}',
	gists_url: 'https://api.github.com/users/arpit8392/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/arpit8392/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/arpit8392/subscriptions',
	organizations_url: 'https://api.github.com/users/arpit8392/orgs',
	repos_url: 'https://api.github.com/users/arpit8392/repos',
	events_url: 'https://api.github.com/users/arpit8392/events{/privacy}',
	received_events_url: 'https://api.github.com/users/arpit8392/received_events',
	type: 'User',
	site_admin: false,
	name: 'Arpit Namdev',
	company: 'Barclays',
	blog: 'www.linkedin.com/in/arpit-namdev',
	location: 'Pune',
	email: 'arpit.namdev@outlook.com',
	hireable: true,
	bio: 'Lead Performance Engineer | Full Stack Web Developer - Next JS | React | Javascript | Typescript | Tailwind CSS | AWS Solution Architect Associate Certified',
	twitter_username: null,
	public_repos: 25,
	public_gists: 0,
	followers: 1,
	following: 1,
	created_at: '2015-11-27T14:31:50Z',
	updated_at: '2023-05-28T11:22:40Z',
}

export const mockedDefault = {
	login: 'octocat',
	id: 583231,
	node_id: 'MDQ6VXNlcjU4MzIzMQ==',
	avatar_url: 'https://avatars.githubusercontent.com/u/583231?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/octocat',
	html_url: 'https://github.com/octocat',
	followers_url: 'https://api.github.com/users/octocat/followers',
	following_url: 'https://api.github.com/users/octocat/following{/other_user}',
	gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
	organizations_url: 'https://api.github.com/users/octocat/orgs',
	repos_url: 'https://api.github.com/users/octocat/repos',
	events_url: 'https://api.github.com/users/octocat/events{/privacy}',
	received_events_url: 'https://api.github.com/users/octocat/received_events',
	type: 'User',
	site_admin: false,
	name: 'The Octocat',
	company: '@github',
	blog: 'https://github.blog',
	location: 'San Francisco',
	email: 'octocat@github.com',
	hireable: null,
	bio: null,
	twitter_username: null,
	public_repos: 8,
	public_gists: 8,
	followers: 9539,
	following: 9,
	created_at: '2011-01-25T18:44:36Z',
	updated_at: '2023-05-22T11:20:34Z',
}
